name:                roc-id
version:             0.1.0.0
license:             BSD3
author:              "Jonathan Knowles"
copyright:           "Jonathan Knowles"
github:              "jonathanknowles/roc-id"
maintainer:          "mail@jonathanknowles.net"

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/jonathanknowles/roc-id#readme>

dependencies:
- MonadRandom
- Only
- base >= 4.7 && < 5
- text
- vector-sized

ghc-options: -Wall

library:
  other-modules: ROC.ID.Utilities
  source-dirs: library

tests:
  roc-id-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - generic-arbitrary
    - hspec
    - roc-id
